import { useState } from 'react';
import { ProgressIndicator } from './ProgressIndicator';
import { FollowUpChat } from './FollowUpChat';
import { MODEL_NAMES, exportAsMarkdown } from '../utils/prompts';
import { MarkdownRenderer } from './MarkdownRenderer';

export function FinalView({ deliberation, onStartNew, apiKeys, settings }) {
    const [copiedMarkdown, setCopiedMarkdown] = useState(false);
    const [copiedContext, setCopiedContext] = useState(false);
    const [expandedRounds, setExpandedRounds] = useState({});

    const toggleRound = (roundNum) => {
        setExpandedRounds(prev => ({
            ...prev,
            [roundNum]: !prev[roundNum]
        }));
    };

    const handleCopyMarkdown = async () => {
        try {
            const markdown = exportAsMarkdown(deliberation);
            await navigator.clipboard.writeText(markdown);
            setCopiedMarkdown(true);
            setTimeout(() => setCopiedMarkdown(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    const handleCopyContext = async () => {
        try {
            const context = `**Original Question:**
${deliberation.query}

**Answer (Synthesized from ${deliberation.enabledModels.length} AI models after ${deliberation.currentRound} rounds of deliberation):**
${deliberation.synthesis?.response || ''}

---
*Context generated by RationaLLM. You can continue this conversation below.*`;

            await navigator.clipboard.writeText(context);
            setCopiedContext(true);
            setTimeout(() => setCopiedContext(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    // Check if user has API keys for follow-up chat
    const hasApiKeys = settings?.useOpenRouter
        ? !!apiKeys?.openrouter
        : deliberation.enabledModels.some(m => apiKeys?.[m]);

    return (
        <div className="max-w-4xl mx-auto">
            <ProgressIndicator
                currentRound={deliberation.currentRound}
                phase="complete"
            />

            <div className="text-center mb-8">
                <h2 className="text-3xl font-bold mb-2 bg-gradient-to-r from-claude via-gpt to-gemini bg-clip-text text-transparent">
                    Deliberation Complete
                </h2>
                <p className="text-text-muted">
                    {deliberation.currentRound} round{deliberation.currentRound > 1 ? 's' : ''} • {deliberation.enabledModels.length} models
                </p>
            </div>

            {/* Original query */}
            <div className="bg-surface-alt rounded-xl border border-border p-6 mb-6">
                <h3 className="font-semibold mb-2 text-text-muted">Original Query</h3>
                <p className="text-text">{deliberation.query}</p>
            </div>

            {/* Rounds (collapsible) */}
            <div className="space-y-4 mb-6">
                {deliberation.rounds.map((round, index) => {
                    const isExpanded = expandedRounds[round.number];

                    return (
                        <div
                            key={round.number}
                            className="bg-surface-alt rounded-xl border border-border overflow-hidden"
                        >
                            <button
                                onClick={() => toggleRound(round.number)}
                                className="w-full px-6 py-4 flex items-center justify-between hover:bg-surface-hover transition-colors"
                            >
                                <span className="font-semibold">Round {round.number}</span>
                                <span className="text-text-muted">
                                    {isExpanded ? '▲' : '▼'}
                                </span>
                            </button>

                            {isExpanded && (
                                <div className="px-6 pb-6 space-y-4 border-t border-border pt-4">
                                    {deliberation.enabledModels.map(modelId => {
                                        const response = round.responses[modelId];
                                        if (!response?.text) return null;

                                        return (
                                            <div key={modelId}>
                                                <h4
                                                    className="font-medium mb-2"
                                                    style={{ color: `var(--color-${modelId})` }}
                                                >
                                                    {MODEL_NAMES[modelId]}
                                                    {response.status && (
                                                        <span className="ml-2 text-xs px-2 py-0.5 rounded bg-surface text-text-muted">
                                                            {response.status.toUpperCase()}
                                                        </span>
                                                    )}
                                                </h4>
                                                <MarkdownRenderer content={response.text} />
                                            </div>
                                        );
                                    })}
                                </div>
                            )}
                        </div>
                    );
                })}
            </div>

            {/* Synthesis */}
            {deliberation.synthesis?.response && (
                <div className="bg-surface-alt rounded-xl border-2 border-gpt p-6 mb-8">
                    <h3 className="font-semibold mb-3 text-gpt">Final Synthesis</h3>
                    <MarkdownRenderer content={deliberation.synthesis.response} />
                </div>
            )}

            {/* Export Actions */}
            <div className="flex flex-wrap gap-4 justify-center mb-8">
                <button
                    onClick={handleCopyContext}
                    className={`
                        px-6 py-3 rounded-xl font-medium transition-all
                        ${copiedContext
                            ? 'bg-[#10a37f] text-white'
                            : 'bg-surface-alt text-text border border-border hover:border-text-muted'
                        }
                    `}
                >
                    {copiedContext ? '✓ Copied!' : '📋 Copy Context'}
                </button>

                <button
                    onClick={handleCopyMarkdown}
                    className={`
                        px-6 py-3 rounded-xl font-medium transition-all
                        ${copiedMarkdown
                            ? 'bg-gpt text-white'
                            : 'bg-surface-alt text-text border border-border hover:border-text-muted'
                        }
                    `}
                >
                    {copiedMarkdown ? '✓ Copied!' : '📄 Export Full Markdown'}
                </button>

                <button
                    onClick={onStartNew}
                    className="px-6 py-3 rounded-xl font-medium bg-gradient-to-r from-claude via-gpt to-gemini text-white hover:opacity-90 shadow-lg"
                >
                    Start New Deliberation
                </button>
            </div>

            {/* Follow-up Chat */}
            {hasApiKeys && deliberation.synthesis?.response && (
                <div className="mb-8">
                    <FollowUpChat
                        query={deliberation.query}
                        synthesis={deliberation.synthesis.response}
                        availableModels={deliberation.enabledModels}
                        apiKeys={apiKeys}
                        useOpenRouter={settings?.useOpenRouter}
                    />
                </div>
            )}

            {/* Manual mode hint */}
            {!hasApiKeys && (
                <div className="text-center text-text-muted text-sm mb-8">
                    <p>💡 Use the "Copy Context" button above to paste into ChatGPT or Claude for follow-up questions.</p>
                </div>
            )}
        </div>
    );
}

